### ISSUE TITLE
MS-700-lab_M02.md New classification labels

### ISSUE THREAD

**Issue by sgtdonny** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#11]
# Module: 02
#### Step: 00

Description of issue
Classification labels has been changed to a new feature and is not compatible to the old ones.
https://docs.microsoft.com/de-de/microsoft-365/compliance/sensitivity-labels-teams-groups-sites

Please Update the lab. Old style make no sense any more.

**Comment by sgtdonny** [comment]
Feature is not any more in preview and old labels are not supported.
https://docs.microsoft.com/de-de/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#classic-azure-ad-group-classification

**Comment by renaudwangler** [comment]
I second @sgtdonny on this : we're on a brand new course and the lab is no more deprecated : it can't be done because it focuses on a now missing feature....

**Comment by MSFTJenny** [comment]
Thank you for the feedback. I've removed the outdated lab tasks for now. We are working on the new labs. Please stay tuned.

**Comment by bramhe** [comment]
Hi Friends

Can someone guide how to practice using these git files.
Need little guidance.

Thanks in advance.
Regards,
Ajay
