### ISSUE TITLE
MS-700 Issue with GDPR Lab

### ISSUE THREAD

**Issue by stilldrey** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#120]
# Module: 02
#### Step: 07

Description of issue: The sensitive info type 'Austria Physical Address' isn't supported for 'Microsoft Defender for Cloud Apps' location currently. It doesn't support the next country (Belgium) either. 

Repro steps:

1. Follow along with what is documented (nothing is mentioned about MS Defender for Cloud Apps) and see what happens
2. If you remove the Cloud Apps from the policy, I received a different error
3. Policy is still created, just an error occurs.
![MS700 Lb 2](https://user-images.githubusercontent.com/31038390/167707774-251a712e-c16a-4f2c-b123-b09216d704d8.jpg)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has resolved this issue with pull requests #131 and #132.
