### ISSUE TITLE
Meeting policy settings in Lab 4, Ex 1

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#168]
# Lab: 04
#### Step: 04

Description of issue

The categories and settings in Meeting policies have changed.

Step 4 should say:

On the **Meetings policies** page, turn **Off** the **Meeting recording** setting under the **Recording & transcription** section.
Repro steps:

1.
1.
1.

**Comment by AnikaMicrosoft** [comment]
Apologies for the delay, the instructions are updated, working on publishing them for users to have the updated instructions.
