### ISSUE TITLE
Retention policy instructions in Lab 2, Exercise 3 need updating.

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#176]
# Module: 02
### Task: 5 and 6

The instructions for creating retention policies are wrong - they no longer match what the students are seeing when they use the wizard.  For example, there is now a page asking the user whether to restrict the policy to an admin unit.

Please could the instructions for using the wizard in each of these tasks be thoroughly checked and corrected?

**Comment by AnnetteGill** [comment]
Just to be clear, this is Lab 2, Ex 3, Tasks 5 and 6.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is now resolved @AnnetteGill
