### ISSUE TITLE
DLP policy instructions need updating in Lab 2, Ex 3

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#177]
# Module: 02
### Task: 8 and 9

The instructions for creating a DLP policy are no longer correct.  For example, there is now a page that asks whether the policy should apply only to a specific admin unit. There are other minor differences, where text has changed.

The students are getting confused because there are so many discrepancies between the instructions and what they are seeing in the wizard.  

Please can the instructions be thoroughly checked and corrected?

**Comment by AnnetteGill** [comment]
Another problem with these instructions is that in the "Locations to apply policy", you're asked to set "Microsoft Defender for Cloud Apps" to Off.  But this option doens't appear in the list of locations.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is now resolved @AnnetteGill
