### ISSUE TITLE
Lab 4 Ex 1, pop-up blocked in browser

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#178]
# Learning Path: 4
#### Step: 2

When you try to create a new Webinar, the pop-up that should open to allow you to configure the webinar is blocked. 

Either the settings for Edge need to be modified to allow pop-ups, or the instructions need to tell the student how to allow pop-ups.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
Could not replicate the issues, it's possible this is now resolved. @AnnetteGill please confirm
