### ISSUE TITLE
Country pick list doesn't appear

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#179]
# Learning Path: 4
### Task: 1 and 4

Several students reported the following problem:

When trying to add an emergency address, and also when requesting phone numbers, you have to choose the country. The students said when they selected the Country or Region field, the pick list of countries did not appear.

It seemed to happen if the Edge browser had been updated in CLIENT1.  In my lab, Edge hasn't been updated, and I can see the pick list.

They said that they either had to clear the browser cache and restart the browser, or open an InPrivate window.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is resolved @AnnetteGill
