### ISSUE TITLE
Lab 4: call queue 

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#180]
# Learning Path: 4
### Task: 2 

Task 2: Create a call queue
Step 10: the name of the resource account is actually "Contoso call queue resource account"

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I beleive this is resolved @AnnetteGill
