### ISSUE TITLE
Lab 4 Call Quality dashboard

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#181]
# Learning Path: 4
#### Step: 2

Step 2 should now read:

In the left-hand navigation pane, expand **Analytics and reports** at the bottom, and then select **Call quality dashboard**.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is resolved @AnnetteGill
