### ISSUE TITLE
Entra admin center replaces AAD portal

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#182]
# Labs 1, 2 and 3

In issue #171 I pointed out that the Azure AD Portal doesn't exist now. Although changes were made to the instructions, there are still some things that need to be changed.

Lab 1, Ex 4, Task 1, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 1, Ex 4, Task 3, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 1, Ex 4, Task 5, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 2, Ex 1, Task 1, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 2, Ex 1, Task 4, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 3, Ex 1, Task 5, step 4: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 3, Ex 1, Task 6, step 1: This should read "Connect to the Client1 VM and browse to Entra admin center (https://entra.microsoft.com/) as MOD Administrator."

Lab 1, Ex 4, Task 1, step 2 : This should now read "On the left navigation pane, select **Identity > Groups > Group settings**"

Lab 1, Ex 4, Task 3, step 2: This should now read "On the left navigation pane, select **Identity > Groups > Group settings**"

Lab 1, Ex 4, Task 5, step 2: This should now read "On the left navigation pane, select **Identity > Groups > Group settings**"

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is resolved @AnnetteGill
