### ISSUE TITLE
Group creation instructions need to be updated

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#183]
# Learning Path: 1
### Exercises: 3 and 4

The instructions for creating groups in the Microsoft 365 Admin center need to be updated in the following tasks:

Lab 1, Ex 3, Task 1

Lab 1, Ex 4, Task 2

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is now resolved @AnnetteGill
