### ISSUE TITLE
Microsoft 365 Defender portal is now called Microsoft Defender

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#184]
# Learning Path: 2
### Task: 1

Steps 1 and 2: A minor issue, but the Microsoft 365 Defender portal has now been renamed Microsoft Defender portal.

I think this is the only place in the labs that references this portal, but I may be wrong.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
I believe this is now resolved @AnnetteGill
