### ISSUE TITLE
Lab 3, blocking an app

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#185]
# Learning Path: 3
#### Steps: 5 and 6

The procedure for blocking the app have changed, so the instructions in steps 5 and 6 need to be updated.

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
Intructions have been updated @AnnetteGill
