### ISSUE TITLE
MS-700-lab_M03_ak / Exercise 01 / Task 02 / Step 11

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#187]
# Module: 03
#### Step: 11

The step 11 command gives an error that "_A parameter cannot be found that matches parameter name 'MembershipType'_". So, unable to create the Private channel via Powershell.

![image](https://github.com/MicrosoftLearning/MS-700-Managing-Microsoft-Teams/assets/133017642/09411682-e329-41c1-b5cc-c0d1d3815559)

**Comment by AnikaMicrosoft** [comment]
working on issue now will report back with the fix.

**Comment by AnikaMicrosoft** [comment]
This should be resolved @Nimra-Maryam
