### ISSUE TITLE
Lab 1, Ex 4 and Lab 2, Ex 3 - Microsoft Graph cmdlets don't work.

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#190]
In Lab 1, Exercise 4, task 2, the numbering of the steps has gone wrong. Step 5 is followed by step 1.

We're asked to install the Microsoft Graph PowerShell module by running Install-Module MicrosoftGraph.  But when you run the MG cmdlets later, none of them work - the commands aren't recognised. I don't think the correct submodules of Microsoft Graph are installed.

I think we have the same problem with Lab 2, Exercise 3, Task 1 - I don't think these cmdlets work either.

**Comment by AnikaMicrosoft** [comment]
acknolwedged. working on issues now.

**Comment by AnikaMicrosoft** [comment]
This should now be resolved. Certain commands have been corrected while others have been removed. Please proceed with using the regular PowerShell commands, and the updated Graph comm and should be completed soon.
