### ISSUE TITLE
MS-700 Classic Teams desktop client out of support on 1st July

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#191]
The two virtual machines in this lab have the Classic version of the Teams desktop client installed.  This goes out of support on 1st July 2024.

Please can the VM images be updated with the new Teams client?

**Comment by AnikaMicrosoft** [comment]
acknowledged. working on issues now.

**Comment by AnikaMicrosoft** [comment]
this should now be updated. Please note that the lab instructions may need to be updated to reflect the changes in the UI with this new Teams client. We are currently working on making any necessary changes to the instructions, but this should not impede students from doing the lab.

**Comment by AnnetteGill** [comment]
Thank you!
