### ISSUE TITLE
LAb 02 Exercise 03 Sensitivity labels are moving to Entra ID

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#192]
# Module: 00
#### Step: 00

Description of issue

You cannot enable sensitivity labels for Groups and Sites. Sensitivity labels have to be shared with Entra.

![image](https://github.com/MicrosoftLearning/MS-700-Managing-Microsoft-Teams/assets/10166617/971ef507-7577-4dc6-ba5f-9b296a9eee97)

![image](https://github.com/MicrosoftLearning/MS-700-Managing-Microsoft-Teams/assets/10166617/b0a5b3cf-55de-4ea9-8b79-662a7516b45a)

Additional reading: 
https://learn.microsoft.com/en-is/entra/identity/jusers/groups-assign-sensitivity-labels

https://learn.microsoft.com/en-us/purview/sensitivity-labels-teams-groups-sites

Repro steps:

1.
1.
1.

**Comment by AnikaMicrosoft** [comment]
Bug triaged. Working on issue now.

**Comment by jonlukewtafe** [comment]
Roughly how long will it be until this issue is fixed?

**Comment by AnikaMicrosoft** [comment]
This is now resolved, more steps have been added to configure the necessary settings in PowerShell
