### ISSUE TITLE
MS-700-lab_M02.md ATP Instructions Outdated

### ISSUE THREAD

**Issue by GradyD** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#2]
# Module: MS-700
#### Step: 02-3

https://security.microsoft.com now takes admins directly to https://protection.office.com/homepage. This means step 3 is no longer needed and step 2 should probably be adjusted to send users directly to https://protection.office.com/homepage and step 4 can be reworded slightly as it is no longer in a new tab.

Step 4 also appears to be missing a few words that have been replaced with ***

![image](https://user-images.githubusercontent.com/994964/70958463-4b851080-2047-11ea-8a70-1448160e081b.png)

**Comment by MSFTJenny** [comment]
Thank you for the suggestions, I fix the formatting issue. 
For the redirection, I wasn't able to repro the issue. We are optimizing the admin experience from **Microsoft 365 security and compliance center** to specialized workspaces: **Microsoft 365 security center** and **Microsoft 365 compliance center** with accessibility and usability design in mind. Thus, those steps are still valid.
