### ISSUE TITLE
Mod 03, new value needed in instructions

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#20]
# Module: 03
#### Steps: 08 & 09

and

# Module: 03ak
#### Steps: 13 &15

Description of issue
New setting added to page in the admin center:
**Internet link capacity**

needs to be added to instructions.

**Comment by MSFTJenny** [comment]
Resolved. Thank you for the feedback!
