### ISSUE TITLE
Mod 02 Exercise 3 Task 3 missing?

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#21]
# Module: 02
#### Step: missing?

Description of issue
The introduction of Exercise 3 ends with: 

> At the end you will perform scoped directory search.

and Step 15 of Task 2 says:

> 15. Leave the browser open for the next task.

But there is no Task 3. If the removal is intentional, remove the last sentence of the intro and change Task 2, Step 15 to "Close all windows."

**Comment by MSFTJenny** [comment]
Resolved. Thank you for the feedback!
