### ISSUE TITLE
Why not use Teams admin center to restore Team?

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#27]
# Module: 04
#### Steps: 05 -13

Description of issue:
Why do we use the Azure admin center to restore the Group instead of the Teams admin center to restore the Team? 
I'll do a pull request if this should be corrected.

**Comment by MSFTJenny** [comment]
There are two different scenarios:

**A team has been deleted**
When a team been deleted, you won't see the team from the Teams admin center. You can retrieve the team by restoring the associated Microsoft 365 group from the Azure admin center. This restores associated content with the M365 group, including the deleted team.

**A team has been archived**
For this scenario, you can unarchive the archived team from the Teams admin center.

Thanks,
