### ISSUE TITLE
Cmdlet fails with error

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#31]
# Module: 02
#### Step: 13

Description of issue
This cmdlet fails with error, "Cannot bind argument to parameter 'Id' because it is null."

I think this is because what were formerly tasks 1 and 2 (classifications) have been removed.  In the old task 1, step 12, you had to run this cmdlet:

   New-AzureADDirectorySetting -DirectorySetting $Setting

If you run this cmdlet before running the Set-AzureADDirectorySetting in the new task 2 step 13, it works without error.

Repro steps:

1. 
1.
1.

**Comment by MSFTJenny** [comment]
Good catch. Thank you!
I've updated the labs.
