### ISSUE TITLE
Network Testing Companion no longer works

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#34]
# Module: 03
#### Step: All

Description of issue
Network Testing Companion no longer works

Getting Time out errors, even installed on my own machine--is it supported anymore?

**Comment by trainu2** [comment]
I've had the same problems/question.  Tried multiple times in the last couple of weeks but same "time out" issues each time.

**Comment by ITBlandMCT** [comment]
Working now.

**Comment by stilldrey** [comment]
Had some issues today with this tool - found some other tools to suggest/recommend to students: https://connectivity.office.com/ and https://docs.microsoft.com/en-us/microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool?view=o365-worldwide#what-happens-at-each-test-step - looks like some better/future connectivity tools.
