### ISSUE TITLE
Lab01 -Ex 1 Task 2 Alex Wilbur

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#35]
# Module: 01
#### Step: 06

Description of issue
Errors when changing Alex's location to Canada
Repro steps:

Skipped change - no work around

**Comment by ITBlandMCT** [comment]
This appears to be a code error in the Microsoft 365 admin center, hopefully to be fixed soon. 
For a work-around, change the location in the **Azure AD admin center**. 
(Note: this change is not needed until Lab 4, when the team (group) **CA-Office** is changed to **_dynamic membership_**.)

**Comment by ITBlandMCT** [comment]
Did the lab today (11/02/2020) and this is no longer a problem.

**Comment by MSFTJenny** [comment]
We should be good on this. Close the issue for now.
