### ISSUE TITLE
The "+ Add cloud storage" button no longer appears.

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#37]
# Module: 05
#### Step: 09

If all external storage options are removed, the "**+ Add cloud storage**" button no longer appears.
(This change makes sense, but the student may be confused unless we show the button to them before we remove it, or we could leave one option selected and verify that the rest are gone.)

**Comment by MSFTJenny** [comment]
Thank you! ITBlandMCT.
We've incorporated your feedback into the lab refresh.
