### ISSUE TITLE
Confusion in Lab 5 re: Google Analytics

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#38]
# Module: 05
#### Task: 03

Description of issue

There are two Google Analytics Apps, suggest blocking both.  Delegates are confused if they block one and the other still shows up when they add an app to test the app permission policy.  Leads them to believe the policy hasn't worked.
![image](https://user-images.githubusercontent.com/32812499/98294748-5f5f9b00-1fa8-11eb-849c-b42a5c132115.png)

**Comment by MSFTJenny** [comment]
Thank you! Sara.
We've incorporated your feedback into the lab refresh.
