### ISSUE TITLE
Format Suggestion

### ISSUE THREAD

**Issue by GradyD** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#4]
# Module: MS-700
#### Step: 0010-13

In steps 1-10 a code blocked is used but steps 10-13 contain powershell and are not within a code block or have any type of "call to action" styling. Is this by design? 

![image](https://user-images.githubusercontent.com/994964/70960157-4080af00-204c-11ea-90c9-d8bd653712e1.png)

**Comment by MSFTJenny** [comment]
Updated the format. Thank you for the suggestion!
