### ISSUE TITLE
Lab 2, Ex 3, DLP policy changes

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#41]
# Module: 02
## Lab: 02
Exercise 3
### Task: 04 and 05

Description of issue

The wizard for creating the Data Loss Prevention policies in the Complance Center has changed.  The instructions no longer work.

**Comment by MSFTJenny** [comment]
Thank you for the feedback. We checked the instructions and updated a few option descriptions. The tasks should be up-to-date.
