### ISSUE TITLE
Lab 2 Ex 1 Task 2 - More Detail Needed

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#43]
# Module: 02
### Ex 01 Task: 02

Description of issue
The instructions on creating the sensitivity labels needs more detail in some of the steps.  

In other exercises the section of the Compliance Center is detailed in the lab instructions but not in this one.

In creating the first sensitivity labels it would be useful to includes steps to tick on the option so that the  settings are available and then the further labels could simply detail the settings to be chosen as current.

**Comment by richardrobb** [comment]
The instructions from Steps 7-72 no longer match the interface. The wizard to create the sensitivity labels ultimately works but requires fumbling around to find options and selections that have been renamed, moved to other pages or just updated. With something this detailed, the instructions +++should be+++ clearer.

**Comment by MSFTJenny** [comment]
Thank you! We refreshed the lab instructions. Please let us know if there's other feedback.
