### ISSUE TITLE
Lab 5, Ex 2, Task 5, Step 2 - Notification Bot link broken

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#45]
# Lab: 05: Modify collaboration settings for Teams, Ex 2, Task 5, Step 2

The link given for the NotificationBot.zip in Step 2. (https://github.com/OfficeDev/msteams-sample-line-of-business-apps-csharp/blob/master/Cross%20Vertical/NotificationBot/Manifest/Notification%20App.zip) is broken. 

Updated link: https://github.com/OfficeDev/msteams-sample-line-of-business-apps-csharp/raw/6f7e5825f2978c87f32a7db2715850fddbd0e1e5/Cross%20Vertical/NotificationBot/Manifest/Notification%20App.zip

**Comment by ITBlandMCT** [comment]
Updated link works and will download the manifest, however the app back-end does not seem to be functioning. :-(

**Comment by mhykgyver** [comment]
having an issue with this as well, my students are having issues uploading the app with Something Went Wrong error, no details whatsoever...screenshot of error as per link: [Something Went Wrong](https://1drv.ms/u/s!AhcPdzfilLvVgYZaVQJAEGC28-ueeA?e=FyJCZCl)

**Comment by stilldrey** [comment]
I had the same problem - found an application that works with VisualSP. 

https://support.visualsp.com/knowledge-base/customize-the-microsoft-teams-app-icons/ - download the zip from here and you can have students complete the lab.

**Comment by MSFTJenny** [comment]
Thank you for the feedback! We updated the lab instructions.
