### ISSUE TITLE
Lab 02: Configure security and compliance for teams and content - PowerShell error

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#46]
#### Step: 10

The PS command Set-AzureADDirectorySetting -Id $Setting.Id -DirectorySetting $Setting is used in 3 different Tasks. 

1: Task 1, Step 12. Creates confusion with the note and should simply use the New-AzureADDirectorySetting -DirectorySetting $Setting cmdlt. 

2: Task 5, Step 11. The cmdlet works correctly

3: Task 8, Step 10. The cmdlet results in a null error 
![image](https://user-images.githubusercontent.com/73357132/103664503-35364500-4f27-11eb-8d7f-847d216bae51.png)

Something like this will work to correct the error in Task 8.
Set-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where {$_.DisplayName -eq 'Group.Unified'}).id -DirectorySetting $setting

**Comment by rlthompson904** [comment]
This is still an issue, is it being addressed?

**Comment by MSFTJenny** [comment]
Thank you for the feedback. We've updated the cmdlet.
