### ISSUE TITLE
No phone numbers showing up

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#53]
# Module: 06
### Task: 3

Description of issue
No phone numbers showing up

Repro steps:

1. Follow lab steps until step 12

Screenshot of error:  ["we cant find any phone numbers for the address you selected error"
](https://1drv.ms/u/s!AhcPdzfilLvVgYZ9rV8VyzP0j-bLNg?e=dE2Poa)

**Comment by stilldrey** [comment]
I ran into this as well - easy fix is to change the location for requesting trial phone numbers (all the students taking this course have exhausted the trial phone numbers available in Redmond, Washington!)

**Comment by MSFTJenny** [comment]
Thank you for the feedback! We updated the lab instructions. Please let us know if the issue still exists.
