### ISSUE TITLE
Hidden teams not visible

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#56]
# Module: 04
#### Step: 12

Description of issue
Hidden teams are not visible. 
Also, the instructions in step 10 tell you to logon as LynneR, then the instructions in step 12 indicates you should be seeing information for Megan.

Repro steps:

1.
1.
1.

**Comment by MSFTJenny** [comment]
Thank you for the feedback! We refreshed the lab instructions. Please let us know if the issue still exists.
