### ISSUE TITLE
Dynamic Query does not return results identified in lab

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#57]
# Module: 04
#### Step: 16

Description of issue
Allan DeYoung is still a member of the group.
Allan should still be a member of the group because his user account is enabled and his usage location is Canada.
All of the users used in the lab were setup in module 1 to be in the Usage Location Canada.
This needs to have steps written to have you change the usage location of Allan, then refresh the group membership.

Repro steps:

**Comment by MSFTJenny** [comment]
Thank you for the feedback! We tested and refreshed the lab instructions. Please let us know if the issue still exists.
