### ISSUE TITLE
PowerApps app creation completely does not work as written

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#58]
# Module: 05: Modify collaboration settings for Teams
#### Step: 9-35

Description of issue:  The creation of PowerApps is now completely different.  None of the steps from 9-35 work any longer.
The entire task instructions need to be rewritten to reflect the new PowerApps portal.

Repro steps:

1.
1.
1.

**Comment by MSFTJenny** [comment]
Thank you! All. We replaced it with a new lab exercise.
