### ISSUE TITLE
Teams room free trial error

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#63]
# Lab 03: 
#### Step: 22

Description of issue
Site error after hitting 'Try now' to purchase a Microsoft Teams Rooms Standard Trial - Step 22.

**Comment by MSFTJenny** [comment]
Thank you! Johnny. We refreshed the lab instructions. Please let us know if the issue still exists.
