### ISSUE TITLE
"Contoso Emergency Address" is used before it is created

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#66]
# Lab/Demo: 06
#### Step: 10

Description of issue

In this step you are told to select the "Contoso Emergency Address". However, this address is not added until later in the lab, Exercise 2, Task 1, Step 5.

It appears this step in Exercise 2 (creating the emergency address) needs to be moved to before the address is used in Exercise 1.

Repro steps:

1. Lab 6, Ex1, Task 3, Step 10: There is no emergency address to select.
1. Lab 6, Ex2, Task 1, Step 5: The address is created in this step.

**Comment by MSFTJenny** [comment]
Thank you for catching the issue! The lab has been updated.
