### ISSUE TITLE
Searching by Location (City Name) is slow/doesn't work.  

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#68]
# Lab/Demo: 06
### Step: 11

**Description of issue:**

I believe this to be far from a blocking issue, and more of an intermittent annoyance to end users. 

This issue we're running into begins at step 11: 

![image](https://user-images.githubusercontent.com/62155069/126250758-fd2a334f-c000-4035-a87f-82b1da93979a.png)

It either takes a long time to search/find new phone numbers to assign to users based on city names, or doesn't find them at all.  

In my experience, I've seen it take anywhere from a couple minutes, to 15 minutes when searching by city name (If results populate at all).  

What I have found to be a great work around/solution is simply using the "search by area code" option.  
The results seem to be instantaneous.

For this I would ask that a note be added that suggests "Search by area code", as an alternative if Searching by City name doesn't resolve in a timely manner.  Honestly, I might just suggest having them search by area code instead. 

**Repro steps:**

1.  Search for location based on city name.  Huntington, Texas was a bit of a sore spot via this search method. 
2.  Search for location based on area code. Now try Huntington, Texas using the area code option (I believe it was 218?).

**Comment by MSFTJenny** [comment]
Thank you! Daniel. I added the area code as an alternative.
