### ISSUE TITLE
We need to remove the Naming Policy!

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#69]
# Module: 04
#### Step: 06

Description of issue
The creation of the Team fails because we still have the naming policy. (We either need to remove the naming policy or name the Team "Group_CA-Office_United States" and the mail nickname would have to be: "Group_CA-Office_UnitedStates".)

Error:
`New-Team : Error occurred while executing
Code: Request_BadRequest
Message: The property is missing a required prefix/suffix per your organization's Group
naming requirements.`

In the previous version of Lab 2, we removed the naming policy at the end of the lab.

**Comment by ITBlandMCT** [comment]
Here is the missing Task (from the old version):
#### Task 8 – Reset Azure AD settings
You can revert any changes in Azure AD unified groups settings to the defaults again. You can do this by loading a blank template and replacing the current configuration with the template. To clean up your test environment after testing, you will now do this and reset all changes you did for Microsoft 365 Groups and Teams.
1. Connect to the **Client 1 VM** with the credentials that have been provided to you.
2. On the taskbar at the bottom of the page, right click the **Start** button and then select **Windows PowerShell**.
3. Connect to the Azure AD in your tenant with the following cmdlet:
   ```powershell
   Connect-AzureAD
   ```
4. When the Sign in window is displayed, sign in as **MOD Administrator** (admin@&lt;YourTenant&gt;.onmicrosoft.com) using the O365 credentials provided to you.
5. To load the unifed group template, use the following cmdlet:
   ```powershell
   $Template = Get-AzureADDirectorySettingTemplate | Where {$_.DisplayName -eq "Group.Unified"}
   ```    
6. Create a blank Azure AD tenant settings object:
   ```powershell
   $Setting = $Template.CreateDirectorySetting()
   ```
7. Check the Azure AD tenant settings configured in the template:
   ```powershell
   $Setting.Values
   ```
8. Review the current configured Azure AD tenant settings for unified groups and note the differences to the values in the "$Setting" variable, that contains the default template settings:
   ```powershell
   (Get-AzureADDirectorySetting).Values
   ```
9. Because you will still need the sensitivity labels at a later point of this lab, activate only them in your settings variable again by using the following command:
   ```powershell
   $Setting["EnableMIPLabels"] = "True"
   ```
10. Apply the settings variable to your current configuration to revert all other changes:
    ```powershell
    Set-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id -DirectorySetting $Setting
    ```
11. Review your configured Azure AD tenant settings again, which are all on default again:
    ```powershell
    (Get-AzureADDirectorySetting).Values 
    ```
12. Disconnect the current session from the Azure Active Directory tenant and close the PowerShell window.

    ```powershell
    Disconnect-AzureAD
    ```

**Comment by ITBlandMCT** [comment]
To correct the problem in the portal:
1.	Sign in at https://aad.portal.azure.com using the admin credentials.
2.	Select “Azure Active Directory”
3.	Select “Groups”
4.	Select “Naming policy”
5.	Select “Delete policy” and then “Yes”
6.	Close Edge.

**Comment by MSFTJenny** [comment]
Thank you! Eric. I just added a task to remove the naming policy in M01-Exercise 4.

**Comment by ITBlandMCT** [comment]
Thx for the quick work!
