### ISSUE TITLE
No Org-wide team in trial account

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#75]
# Lab: 01
#### Step: 03
and
# Lab: 02
#### Step: 06

Description of issue
Microsoft is no longer creating an Org-wide team for the trial account, so the Contoso team is not present in Lab 01, and can't be used for the guest in Lab 02.

**Comment by MSFTJenny** [comment]
Thank you! Eric. We refreshed the lab instructions.
