### ISSUE TITLE
MOD Admin cannot create Teams in the clients

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#76]
# Module: 04
#### Step: 01

Description of issue
MOD Admin cannot create Teams in the clients
Repro steps:

1. Because MOD Admin is the owner, but not a member of the GroupCreators security group, they cannot create Teams in the Teams clients, only the admin centers. This task tries to use the web client. we either need to use Joni (and make it a Public team) or the Teams admin center. (Or, add Mod admin as both the owner AND a member back in Mod 01 Lab.)

**Comment by awillslo** [comment]
Mod 1 Task 2 step 5 may have been mistakenly skipped or did not run properly. This removes the restriction of Group Creation to solely GroupCreators security group.

**Comment by ITBlandMCT** [comment]
Oops! Did not see the updated Mod 01 Lab--Closing this non-issue.
